
import { Toaster } from 'sonner'
import "../globals.css";
import '../../lib/fontawesome';
import { cn } from '@/lib/utils';
import { Sidebar } from '../components/ui/Sidebar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="pt-BR">
      <body className={cn(
        "min-h-screen font-sans antialiased dark",
      )} suppressHydrationWarning >
        <Sidebar />
        {children}
        <Toaster richColors duration={4000} />
      </body>
    </html>
  )
}
